# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #xcversion(version: "~> 10.0.0")
    cert
    sigh
    prepare_release_build_number
    disable_automatic_code_signing
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      target_filter: ".*Runner.*", # matches name or type of a target
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )
    build_app(
      export_method: "app-store",
      workspace: "Runner.xcworkspace", 
      configuration: "Release", 
      scheme: "Runner",
      output_directory: "./build",
      archive_path: "./archives"
    )
    enable_automatic_code_signing
    appcenter_upload(
      api_token: "2eaebc7218e0e852f6fbda0d09caeb76b259aba7",
      ipa: "./build/Runner.ipa",
      app_name: "Dev-Emotion-Tracker",
      owner_name: "sivamuthukumar07-9toj"
    )
  end
end
