# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    xcversion(version: "~> 10.0.0")
    cert
    sigh
    increment_build_number(
      xcodeproj: "Runner.xcodeproj"
    )
    build_app(
      export_method: "app-store",
      workspace: "Runner.xcworkspace", 
      configuration: "Release", 
      scheme: "Runner",
      output_directory: "./build",
      archive_path: "./archives"
    )
    upload_to_testflight
  end
end
